<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\Request\ParamFetcherInterface;

/**
 * CategoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllQueryBuilder(ParamFetcherInterface $paramFetcher)
    {
        $qb = $this->createQueryBuilder('category');
        $filters = !is_null($paramFetcher->get('filters')) ? $paramFetcher->get('filters') : array();

        foreach($filters as $key => $filter) {
            $qb->andWhere("category.$key = :$key")
                ->setParameter($key, $filter);
        }

        // default sorting
        $qb->addOrderBy("category.title", 'ASC');

        return $qb;
    }
}
