<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\Request\ParamFetcherInterface;

/**
 * TherapyRecommendationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TherapyRecommendationRepository extends EntityRepository
{
    public function findAllQueryBuilder(ParamFetcherInterface $paramFetcher)
    {
        $qb = $this->createQueryBuilder('therapyrecommendation');

        //FILTER
        $filters = !is_null($paramFetcher->get('filters')) ? $paramFetcher->get('filters') : array();
        foreach($filters as $key => $filter) {
            $qb->andWhere("therapyrecommendation.$key = :$key")
                ->setParameter($key, $filter);
        }

        // ORDER BY

        // default sorting
        $qb->addOrderBy("therapyrecommendation.title", 'ASC');

        $orderBy = !is_null($paramFetcher->get('order_by')) ? $paramFetcher->get('order_by') : array();
        foreach ($orderBy as $sort => $order) {
            $qb->addOrderBy("therapyrecommendation.$sort", $order);
        }

        return $qb;
    }
}
