<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\Request\ParamFetcherInterface;

/**
 * TrackLogRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TrackLogRepository extends EntityRepository
{
    public function findAllQueryBuilder(ParamFetcherInterface $paramFetcher)
    {
        $qb = $this->createQueryBuilder('track_log');

        // FILTER
        $filters = !is_null($paramFetcher->get('filters')) ? $paramFetcher->get('filters') : array();
        foreach ($filters as $key => $filter) {

            if (strrpos($key, 'IsIn') > 0) {
                $keyName = substr($key, 0, strlen($key) - 4);
                $arrayValues = explode(',', $filter);
                $qb->andWhere($qb->expr()->in("track_log.$keyName", ":$key"))
                    ->setParameter($key, $arrayValues);
            }
            // get range if from or to is set
            else if ($key == 'from') {
                $qb->andWhere("track_log.createdAt >= :$key")
                    ->setParameter($key, $filter);
            }
            else if ($key == 'till') {

                // add one day to get the till date included in results
                $tillDate = new \DateTime($filter);
                $tillDate->add(new \DateInterval('P1D'));
                $filter = $tillDate->format('Y-m-d');

                $qb->andWhere("track_log.createdAt <= :$key")
                    ->setParameter($key, $filter);
            }
            else {
                $qb->andWhere("track_log.$key = :$key")
                    ->setParameter($key, $filter);
            }
        }

        // ORDER BY
        $orderBy = !is_null($paramFetcher->get('order_by')) ? $paramFetcher->get('order_by') : array();
        foreach ($orderBy as $sort => $order) {
            $qb->addOrderBy("track_log.$sort", $order);
        }

        return $qb;
    }


    public function findTracksByListenCount(ParamFetcherInterface $paramFetcher)
    {
        $qb = $this->createQueryBuilder('track_log');

        $qb->select(
            'COUNT(track_log.track) AS listenCount, 
            track_log.track, 
            track_log.therapy, 
            track_log.user, 
            track_log.title'
        );

        // FILTER
        $filters = !is_null($paramFetcher->get('filters')) ? $paramFetcher->get('filters') : array();
        foreach ($filters as $key => $filter) {

            if (strrpos($key, 'IsIn') > 0) {
                $keyName = substr($key, 0, strlen($key) - 4);
                $arrayValues = explode(',', $filter);
                $qb->andWhere($qb->expr()->in("track_log.$keyName", ":$key"))
                    ->setParameter($key, $arrayValues);
            }
            // get range if from or to is set
            else if ($key == 'from') {
                $qb->andWhere("track_log.createdAt >= :$key")
                    ->setParameter($key, $filter);
            }
            else if ($key == 'till') {
                $qb->andWhere("track_log.createdAt <= :$key")
                    ->setParameter($key, $filter);
            }
            else {
                $qb->andWhere("track_log.$key = :$key")
                    ->setParameter($key, $filter);
            }
        }

        // ORDER BY
        $qb->groupBy('track_log.track');
        $qb->orderBy('listenCount');

        return $qb;
    }
}
